/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ImplementationRouteImport } from './routes/implementation'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as SolutionsIdRouteImport } from './routes/solutions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementationRoute = ImplementationRouteImport.update({
  id: '/implementation',
  path: '/implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChallengesRoute,
} as any)
const SolutionsIdRoute = SolutionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact': typeof ImpactRoute
  '/implementation': typeof ImplementationRoute
  '/industry': typeof IndustryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/university': typeof UniversityRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/solutions/$id': typeof SolutionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact': typeof ImpactRoute
  '/implementation': typeof ImplementationRoute
  '/industry': typeof IndustryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/university': typeof UniversityRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/solutions/$id': typeof SolutionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/government': typeof GovernmentRoute
  '/how-it-works': typeof HowItWorksRoute
  '/impact': typeof ImpactRoute
  '/implementation': typeof ImplementationRoute
  '/industry': typeof IndustryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/university': typeof UniversityRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/solutions/$id': typeof SolutionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/challenges'
    | '/citizen'
    | '/government'
    | '/how-it-works'
    | '/impact'
    | '/implementation'
    | '/industry'
    | '/login'
    | '/register'
    | '/report'
    | '/solutions'
    | '/university'
    | '/challenges/$id'
    | '/solutions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/challenges'
    | '/citizen'
    | '/government'
    | '/how-it-works'
    | '/impact'
    | '/implementation'
    | '/industry'
    | '/login'
    | '/register'
    | '/report'
    | '/solutions'
    | '/university'
    | '/challenges/$id'
    | '/solutions/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/challenges'
    | '/citizen'
    | '/government'
    | '/how-it-works'
    | '/impact'
    | '/implementation'
    | '/industry'
    | '/login'
    | '/register'
    | '/report'
    | '/solutions'
    | '/university'
    | '/challenges/$id'
    | '/solutions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  CitizenRoute: typeof CitizenRoute
  GovernmentRoute: typeof GovernmentRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ImpactRoute: typeof ImpactRoute
  ImplementationRoute: typeof ImplementationRoute
  IndustryRoute: typeof IndustryRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  UniversityRoute: typeof UniversityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementation': {
      id: '/implementation'
      path: '/implementation'
      fullPath: '/implementation'
      preLoaderRoute: typeof ImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/solutions/$id': {
      id: '/solutions/$id'
      path: '/$id'
      fullPath: '/solutions/$id'
      preLoaderRoute: typeof SolutionsIdRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface ChallengesRouteChildren {
  ChallengesIdRoute: typeof ChallengesIdRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesIdRoute: ChallengesIdRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsIdRoute: typeof SolutionsIdRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsIdRoute: SolutionsIdRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  CitizenRoute: CitizenRoute,
  GovernmentRoute: GovernmentRoute,
  HowItWorksRoute: HowItWorksRoute,
  ImpactRoute: ImpactRoute,
  ImplementationRoute: ImplementationRoute,
  IndustryRoute: IndustryRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  UniversityRoute: UniversityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
